#!/bin/bash

# Kiểm tra xem script có được source hay không
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    echo "Lỗi: Script này chỉ được phép source, không được phép chạy trực tiếp."
    exit 1
fi

# Thoát nếu có lỗi
set -e

echo "Cập nhật cấu hình nwg-look..."

# Khai báo biến
THEMES_DIR="$HOME/.local/share/themes"
THEME_FULL_NAME="${THEME_NAME}-${THEME_FLAVOR}-${THEME_ACCENT}"
THEME_DIR="$THEMES_DIR/${THEME_FULL_NAME}"

BASE_URL="https://github.com/catppuccin/gtk/releases/download"
RELEASE="v1.0.3"
OUTPUT_FILE_NAME="${THEME_FULL_NAME}-standard+default.zip"
OUTPUT_DIR_NAME="${THEME_FULL_NAME}-standard+default"
DOWNLOAD_URL="${BASE_URL}/${RELEASE}/$OUTPUT_FILE_NAME"
OUTPUT_FILE="$THEMES_DIR/$OUTPUT_FILE_NAME"

# Xóa các file theme cũ
mkdir -p "$THEMES_DIR"
rm -rf "$THEMES_DIR/${THEME_FULL_NAME}"*

# Tải về Catppuccin theme
if _download_with_retry "$DOWNLOAD_URL" "$OUTPUT_FILE"; then
    # Giải nén và xóa file zip
    unzip -q "$OUTPUT_FILE" -d "$THEMES_DIR"
    rm -f "$OUTPUT_FILE"

    # Đổi tên thư mục theme (bỏ suffix -standard+default)
    mv "$THEMES_DIR/$OUTPUT_DIR_NAME" "$THEME_DIR"

    # Thêm support cho libadwaita
    mkdir -p "${HOME}/.config/gtk-4.0" &&
    ln -sf "${THEME_DIR}/gtk-4.0/assets" "${HOME}/.config/gtk-4.0/assets" &&
    ln -sf "${THEME_DIR}/gtk-4.0/gtk.css" "${HOME}/.config/gtk-4.0/gtk.css" &&
    ln -sf "${THEME_DIR}/gtk-4.0/gtk-dark.css" "${HOME}/.config/gtk-4.0/gtk-dark.css"

    echo "Cài đặt Catppuccin theme hoàn tất!"
else
    exit 1
fi

mkdir -p "$HOME"/.config/nwg-look
rm -rf "$HOME"/.config/nwg-look/*

# Tạo config file động với FLAVOR và ACCENT hiện tại
echo "Tạo nwg-look gsettings file..."

# Tạo thư mục nwg-look nếu chưa có
mkdir -p "$HOME/.local/share/nwg-look"

# Tạo gsettings file cho nwg-look
cat > "$HOME/.local/share/nwg-look/gsettings" << EOF
# Generated by nwg-look, do not edit this file.
gtk-theme=${THEME_FULL_NAME}
icon-theme=Tela-circle-dracula-dark
font-name=Cantarell 10
cursor-theme=Bibata-Modern-Ice
cursor-size=24
toolbar-style=icons
toolbar-icons-size=large
font-hinting=full
font-antialiasing=rgba
font-rgba-order=rgb
text-scaling-factor=1.0
color-scheme=prefer-dark
event-sounds=true
input-feedback-sounds=false
EOF

# Reload
nwg-look -a > /dev/null 2>&1
