#!/bin/bash

# Exit on error
set -e

# Get app path
APP_DIR="$(cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")" && pwd)"
export APP_DIR

# Source environment variables
source "$APP_DIR/env/app"
source "$APP_ENV_DIR/theme"

# Source utility functions
source "$APP_SETUP_UTILS_DIR/download.sh"
source "$APP_SETUP_UTILS_DIR/sync-contents.sh"

# Create symlink
ln -sf "$APP_DIR"/run "$HOME/.local/bin/$APP_NAME_LOWER"

# Function to show usage
show_usage() {
    echo "Usage: $APP_NAME_LOWER [OPTIONS]"
    echo ""
    echo "Options:"
    echo "  --help, -h          Show help"
    echo "  --install, -i       Install packages and configuration"
    echo "  --update, -u        Update specific configuration or all"
    echo "  --exec, -x          Execute script"
}

# Process command line arguments
if [[ $# -eq 0 ]]; then
    show_usage
    exit 0
else
    case "$1" in
        --help|-h)
            show_usage
            exit 0
            ;;
        --install|-i)
            source "$APP_SETUP_DIR/install.sh" "$@"
            ;;
        --update|-u)
            source "$APP_SETUP_DIR/update.sh" "$@"
            ;;
        --exec|-x)
            source "$APP_SCRIPTS_DIR/exec.sh" "$@"
            ;;
        *)
            echo "Error: Invalid option '$1'"
            show_usage
            exit 1
            ;;
    esac
fi
