#!/bin/bash

[[ "${BASH_SOURCE[0]}" != "${0}" ]] || { echo -e "[\033[31m ERRO \033[0m] This script cannot be executed directly." 1>&2; exit 1; }

set -euo pipefail

log_info "Updating nwg-look configuration..."

# Declare variables
THEMES_DIR="$HOME/.local/share/themes"
THEME_FULL_NAME="${THEME_NAME}-${THEME_FLAVOR}-${THEME_ACCENT}"
THEME_DIR="$THEMES_DIR/${THEME_FULL_NAME}"

BASE_URL="https://github.com/catppuccin/gtk/releases/download"
RELEASE="v1.0.3"
OUTPUT_FILE_NAME="${THEME_FULL_NAME}-standard+default.zip"
OUTPUT_DIR_NAME="${THEME_FULL_NAME}-standard+default"
DOWNLOAD_URL="${BASE_URL}/${RELEASE}/$OUTPUT_FILE_NAME"
OUTPUT_FILE="$THEMES_DIR/$OUTPUT_FILE_NAME"

# Clean up themes directory
mkdir -p "$THEMES_DIR"
rm -rf "$THEMES_DIR/${THEME_FULL_NAME}"*

# Download Catppuccin theme
if util_download_with_retry "$DOWNLOAD_URL" "$OUTPUT_FILE"; then
    # Unzip and remove zip file
    unzip -q "$OUTPUT_FILE" -d "$THEMES_DIR"
    rm -f "$OUTPUT_FILE"

    # Rename theme directory (remove -standard+default suffix)
    mv "$THEMES_DIR/$OUTPUT_DIR_NAME" "$THEME_DIR"

    # Add support for libadwaita
    mkdir -p "${HOME}/.config/gtk-4.0" &&
    ln -sf "${THEME_DIR}/gtk-4.0/assets" "${HOME}/.config/gtk-4.0/assets" &&
    ln -sf "${THEME_DIR}/gtk-4.0/gtk.css" "${HOME}/.config/gtk-4.0/gtk.css" &&
    ln -sf "${THEME_DIR}/gtk-4.0/gtk-dark.css" "${HOME}/.config/gtk-4.0/gtk-dark.css"

    log_ok "Catppuccin theme installed successfully!"
else
    exit 1
fi

mkdir -p "$HOME"/.config/nwg-look
rm -rf "$HOME"/.config/nwg-look/*

# Create dynamic config file with current flavor and accent
log_info "Creating nwg-look gsettings file..."

# Create nwg-look directory if it doesn't exist
mkdir -p "$HOME/.local/share/nwg-look"

# Create gsettings file for nwg-look
cat > "$HOME/.local/share/nwg-look/gsettings" << EOF
# Generated by nwg-look, do not edit this file.
gtk-theme=${THEME_FULL_NAME}
icon-theme=Tela-circle-dracula-dark
font-name=Cantarell 10
cursor-theme=Bibata-Modern-Ice
cursor-size=24
toolbar-style=icons
toolbar-icons-size=large
font-hinting=full
font-antialiasing=rgba
font-rgba-order=rgb
text-scaling-factor=1.0
color-scheme=prefer-dark
event-sounds=true
input-feedback-sounds=false
EOF

# Reload
nwg-look -a > /dev/null 2>&1
